### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by BouweCeunen** [mlabouardy/komiser#65]
I am getting mixed content in Chrome, meaning resources are fetched with http instead of https. 

![image](https://user-images.githubusercontent.com/5576686/57329301-ca11eb00-7113-11e9-92e0-0903fd9ef423.png)

**Comment by mlabouardy** [comment]
@BouweCeunen fixed, I also released the support of GCP

**Comment by BouweCeunen** [comment]
I'm still getting this issue on following urls: 

- http://komiser-assets.s3.eu-west-3.amazonaws.com/fonts/line-awesome.woff2
- http://komiser-assets.s3.eu-west-3.amazonaws.com/fonts/line-awesome.woff
- http://komiser-assets.s3.eu-west-3.amazonaws.com/fonts/line-awesome.ttf

**Comment by mlabouardy** [comment]
@BouweCeunen sorry about that, it should be fixed now (cdn issue)
